Repository neo-jgrec/my_teams, pull requests merged in 2024-04, with the labels that each got.

#1 Protocol
  include/events.h
  libs/protocol/Makefile
  libs/protocol/Makefile_colors.mk
  libs/protocol/include/protocol.h
  libs/protocol/src/client/p_client_close.c
  libs/protocol/src/client/p_client_create.c
  libs/protocol/src/client/p_client_listen.c
  libs/protocol/src/client/p_client_send_packet.c
  libs/protocol/src/p_create_payload.c
  libs/protocol/src/server/p_server_close.c
  libs/protocol/src/server/p_server_create.c
  libs/protocol/src/server/p_server_listen.c
  libs/protocol/src/server/p_server_send_packet.c
  libs/protocol/src/server/utils/get_client.c
  libs/protocol/src/server/utils/new_client.c
  libs/protocol/src/server/utils/select_server.c
  libs/protocol/src/server/utils/server_bind.c
  libs/protocol/src/server/utils/server_listen.c
  libs/protocol/src/server/utils/server_setsockopt.c
  libs/protocol/src/server/utils/server_socket.c
  tests/Makefile
  tests/client/Makefile
  tests/client/Makefile_colors.mk
  tests/client/include/client.h
  tests/client/src/main.c
  tests/server/Makefile
  tests/server/Makefile_colors.mk
  tests/server/include/server.h
  tests/server/src/main.c
Labels: enhancement

#2 Server
  client/Makefile
  include/events.h
  server/Makefile
  server/include/commands.h
  server/include/server.h
  server/src/commands/created.c
  server/src/commands/info.c
  server/src/commands/list.c
  server/src/commands/list_team.c
  server/src/commands/logged.c
  server/src/commands/miscellaneous.c
  server/src/main.c
  server/src/response/basic.c
  server/src/server.c
  server/src/uuid.c
Labels: enhancement

#3 feat(server): add event initialize with other client.
  include/events.h
  libs/protocol/include/protocol.h
  libs/protocol/src/client/p_client_listen.c
  libs/protocol/src/client/p_client_send_packet.c
  libs/protocol/src/p_create_payload.c
  libs/protocol/src/server/p_server_listen.c
  libs/protocol/src/server/p_server_send_packet.c
  server/Makefile
  server/include/commands.h
  server/include/server.h
  server/src/commands/created.c
  server/src/commands/logged.c
  server/src/commands/miscellaneous.c
  server/src/utils/basic.c
  server/src/utils/is_in.c
  server/src/utils/uuid.c
Labels: enhancement

#4 refactor(event): improve return type and architecture.
  include/events.h
  server/Makefile
  server/include/server.h
  server/src/commands/created.c
  server/src/commands/info.c
  server/src/commands/list.c
  server/src/commands/list_team.c
  server/src/commands/logged.c
  server/src/commands/miscellaneous.c
  server/src/utils/basic.c
  server/src/utils/sender.c
Labels: enhancement

#5 docs(database): add the mermaid diagram.
  docs/database/Database.md
Labels: documentation

#6 server
  server/include/server.h
  server/src/commands/created.c
  server/src/commands/info.c
  server/src/commands/list.c
  server/src/commands/miscellaneous.c
Labels: enhancement

#8 fix(p_client): make the read non-blocking
  libs/protocol/src/client/p_client_listen.c
Labels: bug

#9 refactor(p_client_listen): do not malloc for better memory management
  libs/protocol/include/protocol.h
  libs/protocol/src/client/p_client_listen.c
  tests/client/src/main.c
Labels: enhancement

#10 refactor(p_create_payload): add robustness
  libs/protocol/src/p_create_payload.c
Labels: enhancement

#12 fix(payload): invalid listen for the client and server not setting co…
  libs/protocol/include/protocol.h
  libs/protocol/src/client/p_client_listen.c
  libs/protocol/src/p_create_payload.c
  libs/protocol/src/server/p_server_close.c
  server/include/server.h
  server/src/commands/created.c
  server/src/commands/info.c
  server/src/commands/list.c
  server/src/commands/list_team.c
  server/src/commands/logged.c
  server/src/commands/miscellaneous.c
  server/src/server.c
  server/src/utils/sender.c
  tests/client/src/main.c
  tests/server/src/main.c
Labels: bug

#13 Packet
  libs/protocol/Makefile
  libs/protocol/include/protocol.h
  libs/protocol/src/client/p_client_close.c
  libs/protocol/src/client/p_client_create.c
  libs/protocol/src/client/p_client_listen.c
  libs/protocol/src/client/p_client_send_packet.c
  libs/protocol/src/p_create_payload.c
  libs/protocol/src/server/p_server_close.c
  libs/protocol/src/server/p_server_create.c
  libs/protocol/src/server/p_server_listen.c
  libs/protocol/src/server/p_server_send_packet.c
  libs/protocol/src/server/utils/get_client.c
  libs/protocol/src/server/utils/new_client.c
  libs/protocol/src/server/utils/select_server.c
  libs/protocol/src/server/utils/server_bind.c
  libs/protocol/src/server/utils/server_listen.c
  libs/protocol/src/server/utils/server_setsockopt.c
  libs/protocol/src/server/utils/server_socket.c
  server/Makefile
  server/include/server.h
  server/src/commands/created.c
  server/src/commands/info.c
  server/src/commands/list.c
  server/src/commands/list_team.c
  server/src/commands/logged.c
  server/src/commands/miscellaneous.c
  server/src/server.c
  server/src/utils/is_in.c
  server/src/utils/sender.c
  tests/client/src/main.c
  tests/server/src/main.c
Labels: bug, enhancement, invalid

#14 build(lib): remove rpath and use library instead of shared library fo…
  client/Makefile
  libs/protocol/Makefile
  server/Makefile
  tests/client/Makefile
  tests/server/Makefile
Labels: invalid

#15 feat(client): first glimpse of client implementation (PR for FU)
  client/Makefile
  client/include/client.h
  client/include/commands.h
  client/src/client.c
  client/src/commands/help.c
  client/src/commands/login.c
  client/src/commands/logout.c
  client/src/logger.c
  client/src/queue/add.c
  client/src/queue/process.c
  client/src/utils/payload_to_zero.c
  libs/protocol/Makefile
  server/src/server.c
Labels: enhancement

#17 feat(select): use select.
  libs/protocol/include/protocol.h
  libs/protocol/src/client/p_client_create.c
  libs/protocol/src/client/p_client_listen.c
  libs/protocol/src/client/p_client_send_packet.c
Labels: enhancement

#18 fix(commands): handle when command is null
  client/src/client.c
Labels: bug

#19 fix(load): break on empty file.
  server/src/server.c
  server/src/utils/load.c
Labels: bug

#20 feat(error): rewrite error code return.
  libs/protocol/Makefile
  libs/protocol/include/protocol.h
  libs/protocol/src/server/p_server_send_packet.c
  server/include/server.h
  server/src/commands/created.c
  server/src/commands/info.c
  server/src/commands/list.c
  server/src/commands/list_team.c
  server/src/commands/logged.c
  server/src/commands/miscellaneous.c
  server/src/server.c
  tests/server/src/main.c
Labels: enhancement

#21 Struct
  client/src/commands/logout.c
  include/events.h
  include/events_structures.h
  server/Makefile
  server/include/server.h
  server/src/commands/created.c
  server/src/commands/info.c
  server/src/commands/list.c
  server/src/commands/list_team.c
  server/src/commands/logged.c
  server/src/commands/miscellaneous.c
  server/src/utils/check.c
  server/src/utils/is_in.c
Labels: enhancement, invalid

#22 fix(server): missing value to be set.
  include/events_structures.h
  server/src/commands/created.c
  server/src/commands/list.c
  server/src/commands/miscellaneous.c
Labels: bug

#24 fix(server): invalid load and handle invalid save file, add debug pri…
  .gitignore
  libs/protocol/src/server/p_server_create.c
  server/Makefile
  server/include/server.h
  server/src/commands/created.c
  server/src/commands/list.c
  server/src/commands/list_team.c
  server/src/commands/logged.c
  server/src/commands/miscellaneous.c
  server/src/server.c
  server/src/utils/clear.c
  server/src/utils/load.c
  server/src/utils/save.c
  server/src/utils/uuid.c
Labels: bug, invalid

#25 feat(client): add latest features of client
  client/Makefile
  client/include/client.h
  client/include/logger.h
  client/include/logger_error.h
  client/src/client.c
  client/src/commands/create.c
  client/src/commands/help.c
  client/src/commands/info.c
  client/src/get_args.c
  client/src/queue/add.c
  client/src/queue/process.c
  client/src/utils/payload_to_zero.c
  include/events.h
  libs/protocol/include/protocol.h
  libs/protocol/src/client/p_client_create.c
  libs/protocol/src/client/p_client_listen.c
Labels: bug, enhancement, invalid

#26 fix(server): update error handling.
  server/include/server.h
  server/src/commands/created.c
  server/src/commands/info.c
  server/src/commands/list.c
  server/src/commands/list_team.c
  server/src/commands/logged.c
  server/src/commands/miscellaneous.c
  server/src/server.c
  server/src/utils/check.c
Labels: enhancement, invalid

#27 feat(client): all client
  client/src/client.c
  client/src/commands/create.c
  client/src/commands/help.c
  client/src/commands/login.c
  client/src/commands/subscribe.c
  client/src/commands/subscribed.c
  libs/protocol/src/client/p_client_listen.c
Labels: enhancement

#28 merge(docs): Add rfc doc and readme file
  README.md
  docs/database/Database.md
  docs/protocol/PROTOCOL.md
  docs/rfc.txt
Labels: documentation

#29 fix(subscribe): missing load of subscribe data and invalid return.
  include/events_structures.h
  server/src/commands/created.c
  server/src/commands/list.c
  server/src/utils/load.c
Labels: bug, enhancement

#30 feat(debug): add more debug print in the server side.
  include/events_structures.h
  server/src/commands/created.c
  server/src/utils/check.c
  server/src/utils/is_in.c
Labels: bug, enhancement
